name: 'jira-integration'
description: 'Helps connecting pull requests to jira including comments on the
  pull request and title validation'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  jira-base-url:
    description: 'Base URL for Jira instance'
    required: false
    default: 'https://mapcolonies.atlassian.net'
  jira-issue-pattern:
    description: 'Regex pattern for Jira issue IDs'
    required: false
    default: 'MAPCO-[0-9]+'
  bypass-labels:
    description: 'Comma-separated list of labels that bypass Jira validation'
    required: false
