name: 'New action template'
description: 'A template for creating new GitHub Actions'

runs:
  using: 'node20'
  main: 'dist/new-action-template/index.js'

inputs:
  greeting:
    description: 'Greeting message'
    required: false
    default: 'Hello'
